dreamly.security:
  # 权限规则配置：表示用{http-method}方法请求的{path}路径必须具备什么{expression}
  spec-list:
    - http-method: ANY
      path: /login
      expression: "anon()"
    - http-method: ANY
      path: /user
      expression: "hasRole('user')"
    - http-method: ANY
      path: /user-no-access
      expression: "hasAllRoles('user','admin','xx')"
    - http-method: ANY
      path: /**
      expression: "hasLogin()"
    - http-method: ANY
      path: /**
      expression: "hasPermission('permission')"
  jwt:
    # jwt sign算法
    algorithm: hs512
    # jwt secret
    secret: http-security-secret-http-security-secret
    # jwt 有效时间
    expiration-in-second: 1209600
